on:
  push:
    branches: [develop]

jobs:
  get-merged-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get merged PRs with label "TESTED"
        run: |
          git fetch --prune origin +refs/heads/*:refs/heads/*
          merged_prs=$(git log --merges --oneline --decorate origin/develop..origin/main --grep="label: TESTED" | cut -d ' ' -f 1)
          echo "Merged PRs with TESTED label: $merged_prs"

          # Store the list of PRs in an output variable
          echo "merged_prs=$merged_prs" >> $GITHUB_OUTPUT

  create-pr:
    runs-on: ubuntu-latest
    needs: get-merged-prs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get list of merged PRs from output
        run: echo "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: "Merge tested changes from develop to int"
          body: "This PR merges all tested changes from develop to int branch."
          head: develop
          base: int
          draft: false
          create_branch: true
